[theme]
primaryColor = "#f87171"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1e1e1e"
textColor = "#e0e0e0"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
